### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by charlicruz** [mdh266/RandomForests#10]
Hi,
I get errors trying to install your library. Do you have any suggestion? thanks

Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    setup(use_pyscaffold=True)
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/Users//opt/anaconda3/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 425, in __init__
    k: v for k, v in attrs.items()
  File "/Users//opt/anaconda3/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 706, in finalize_options
    ep.load()(self)
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 713, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/pyscaffold/integration.py", line 105, in pyscaffold_keyword
    version_keyword(dist, keyword, setuptools_scm_config(value))
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/pyscaffold/contrib/setuptools_scm/integration.py", line 17, in
    dist.metadata.version = get_version(**value)
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/pyscaffold/contrib/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/Users//opt/anaconda3/lib/python3.7/site-packages/pyscaffold/contrib/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/Users/carloscruz/Downloads/RandomForests-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

**Comment by mdh266** [comment]
Thanks for point this out!  

It seems downloading it causes some issues with metadata.  I'll take a look at how to resolve it.

For the time being are you able to clone the repo, i.e. run "git clone https://github.com/mdh266/RandomForests.git".  Then install from the created folder using "python setup.py install".  This worked for me.

**Comment by charlicruz** [comment]
thanks for your quick response. By using git this worked for me. I  when trying to run python setup.py install and 
and python setup.py test. The following error appeared. Do you have any suggestion? thanks: 
ImportError: cannot import name 'RandomForestClassifier' from 'randomforests' (/Users//opt/anaconda3/lib/python3.7/site-packages/randomforests-0.0.post0.dev93+g0330968-py3.7.egg/randomforests/__init__.py)

**Comment by charlicruz** [comment]
I modified from randomforests import RandomForestClassifier to from sklearn.ensemble.forest import RandomForestClassifier
I also get this error: ValueError: Invalid parameter forest for estimator Pipeline(memory=None, steps=[('tree',

**Comment by mdh266** [comment]
Is that from the README or tests? 

There were a few typos in the README that I just fixed.  Should be "from randomforests.ForestClassifier import RandomForestClassifier".

**Comment by charlicruz** [comment]
Thanks a lot. It works!!!!

**Comment by mdh266** [comment]
np! i'll probably update this again soon, noticing some things were missing
